---
aur_installed_packages:
  - catppuccin-gtk-theme
  - google-chrome
  - htop-vim
  - intellij-idea-ultimate-edition
  - intellij-idea-ultimate-edition-jre
  - nerd-fonts-roboto-mono
  - nvm
  - slack-desktop
  - touchegg
  - yay
aur_services:
  - touchegg
aur_user: sjoerd

pacman_installed_packages:
  - alsa-utils
  - base
  - base-devel
  - bluez-utils
  - checkbashisms
  - dash
  - dhcpcd
  - docker
  - dunst
  - dzen2
  - feh
  - firefox-developer-edition
  - git
  - grub
  - gtk-engine-murrine
  - helm
  - jdk17-openjdk
  - jdk21-openjdk
  - kubectl
  - linux
  - linux-firmware
  - linux-headers
  - mediainfo
  - minikube
  - mpv
  - nnn
  - openssh
  - otf-font-awesome
  - pass
  - pulseaudio-alsa
  - pulseaudio-bluetooth
  - ripgrep
  - scrot
  - sxhkd
  - tmux
  - ttf-roboto
  - ttf-roboto-mono
  - unclutter
  - xautolock
  - xclip
  - xf86-video-amdgpu
  - xf86-video-intel
  - xorg-server
  - xorg-xinit
  - xorg-xprop
  - xorg-xrandr
  - zathura
  - zathura-pdf-mupdf
  - zsh
pacman_services:
  - docker
  - bluetooth

system_user: sjoerd
system_groups: docker,users,wheel
