---
- name: Converge
  hosts: all
  gather_facts: false

  roles:
    - role: system
      vars:
        system_root_user: root
        system_root_pass: ""
        system_user: user
        system_pass: resu
        system_installed_keys:
          - rsa
