---
- name: Install git.
  become: true
  community.general.pacman:
    name: git
    state: present

- name: Check if git exists.
  ansible.builtin.stat:
    path: "{{ dots_git_dest }}/.git"
  register: git_exists

- name: Clone/update dots.
  ansible.builtin.git:
    clone: "{{ not git_exists.stat.exists }}"
    dest: "{{ (not git_exists.stat.exists) | ternary(dots_git_dest + '/dots', dots_git_dest) }}"
    repo: "{{ dots_git_repo }}"
    version: master
    force: true
  changed_when: not git_exists.stat.exists

- name: Install dots.
  when: not git_exists.stat.exists
  block:
    - name: Clone dots.
      ansible.builtin.git:
        dest: "{{ dots_git_dest }}/dots"
        repo: "{{ dots_git_repo }}"
        version: master

    - name: Find dots.
      ansible.builtin.find:
        paths: "{{ dots_git_dest }}/dots"
        file_type: any
        hidden: true
      register: dot_files

    - name: Move dots.
      ansible.builtin.copy:
        remote_src: true
        src: "{{ item.path }}"
        dest: "{{ dots_git_dest }}"
        mode: "{{ '0755' if item.isdir else '0644' }}"
      loop: "{{ dot_files.files }}"

    - name: Remove old dots folder.
      ansible.builtin.file:
        path: "{{ dots_git_dest }}/dots"
        state: absent

- name: Create .zprofile symlink.
  ansible.builtin.file:
    src: "{{ dots_git_dest }}/.profile"
    dest: "{{ dots_git_dest }}/.zprofile"
    state: link

- name: X11 configuration.
  block:
    - name: Ensure xorg.config.d folder exists.
      become: true
      ansible.builtin.file:
        path: /etc/X11/xorg.conf.d
        state: directory
        mode: "0755"
        group: root
        owner: root

    - name: Find X11 configuration files.
      ansible.builtin.find:
        paths: "{{ dots_git_dest }}/.config/X11"
        pattern: "*.conf"
      register: found_config

    - name: Create xorg configuration symlinks.
      become: true
      ansible.builtin.file:
        src: "{{ dots_git_dest }}/.config/X11/{{ item | basename }}"
        dest: "/etc/X11/xorg.conf.d/{{ item | basename }}"
        state: link
      loop: "{{ found_config.files | map(attribute='path') | sort }}"

- name: Enable shortcut commands.
  ansible.builtin.command:
    chdir: "{{ dots_git_dest }}/.local/scripts"
    cmd: "./shc"
  environment:
    XDG_CONFIG_HOME: "{{ dots_git_dest }}/.config"
  changed_when: false

- name: Enable ssh-agent daemon.
  ansible.builtin.command:
    chdir: "{{ dots_git_dest }}/.config/systemd/user"
    cmd: "{{ dots_ssh_agent_cmd }}"
  changed_when: false
