---
- name: Install suckless build dependencies.
  become: true
  community.general.pacman:
    name: "{{ suckless_dependencies }}"
    state: present

- name: Install tools.
  ansible.builtin.include_tasks:
    file: tools.yml
  loop: "{{ suckless_installed_tools }}"
  loop_control:
    loop_var: tool
  when: suckless_installed_tools | length > 0
