---
- name: Set current tool.
  ansible.builtin.set_fact:
    suckless_tool: "{{ tool }}"

- name: Clone the tool.
  ansible.builtin.git:
    dest: "{{ suckless_git_dest }}/{{ suckless_tool }}"
    repo: "{{ suckless_git_repo }}/{{ suckless_tool }}.git"
    version: master
    update: "{{ suckless_redo }}"
    force: "{{ suckless_redo }}"
  notify:
    - Find patches.
    - Apply patches.
    - Build tool.

- name: Add remote upstream to git repository.  # noqa command-instead-of-module
  ansible.builtin.command:
    cmd: "git remote add upstream https://git.suckless.org/{{ suckless_tool }}"
    chdir: "{{ suckless_git_dest }}/{{ suckless_tool }}"
  register: tool_upstream
  changed_when: tool_upstream.rc == 0
  failed_when:
    - tool_upstream.rc != 0
    - tool_upstream.stderr | default('') is not search("remote .* already exists")

- name: Ensure /usr/share/applications exists.
  become: true
  ansible.builtin.file:
    path: /usr/share/applications
    state: directory
    mode: "0755"
  when: suckless_tool == 'sxiv'

- name: Find & apply patches for the tool.
  ansible.builtin.meta: flush_handlers

- name: Get install path of the tool.
  ansible.builtin.stat:
    path: "/usr/local/bin/{{ suckless_tool }}"
  register: is_installed

- name: Ensure the tool is installed.
  ansible.builtin.assert:
    that: is_installed.stat.exists

- name: Unset current tool.
  ansible.builtin.set_fact:
    suckless_tool:
