---
- name: Install git.
  become: true
  community.general.pacman:
    name: git
    state: present

- name: Install firefox.
  become: true
  community.general.pacman:
    name: "{{ firefox_package }}"
    state: present

- name: Clone SimpleFox.
  ansible.builtin.git:
    dest: "{{ firefox_simplefox_git_dest }}"
    repo: "{{ firefox_simplefox_git_repo }}"
    version: master

- name: Add remote upstream to git repository.  # noqa command-instead-of-module
  ansible.builtin.command:
    cmd: "git remote add upstream https://github.com/migueravila/SimpleFox"
    chdir: "{{ firefox_simplefox_git_dest }}"
  register: simplefox_upstream
  changed_when: simplefox_upstream.rc == 0
  failed_when:
    - simplefox_upstream.rc != 0
    - simplefox_upstream.stderr | default("") is not search("remote .* already exists")

- name: Make profiles.
  ansible.builtin.include_tasks:
    file: profile.yml
  loop: "{{ firefox_profiles }}"
