---
neovim_bootstrap_cmd: >
  nvim --headless "+Lazy! sync" +quitall
neovim_bootstrap_result: "{{ ansible_env.HOME }}/.local/share/nvim/lazy"

neovim_mason_cmd: >
  nvim --headless "+MasonInstall shellcheck" +quitall
neovim_mason_result: "{{ ansible_env.HOME }}/.local/share/nvim/mason"
