---
firefox_package: firefox-developer-edition
firefox_config_path: "{{ ansible_env.HOME }}/.mozilla/firefox"
firefox_redo: false

firefox_general_prefs:
  - name: toolkit.legacyUserProfileCustomizations.stylesheets
    value: true
  - name: layers.acceleration.force-enabled
    value: true
  - name: gfx.webrender.all
    value: true
  - name: svg.context-properties.content.enabled
    value: true

firefox_profiles:
  - name: personal
    prefs: "{{ firefox_general_prefs }}"
  - name: work
    prefs: "{{ firefox_general_prefs }}"

firefox_simplefox_git_dest: "{{ ansible_env.HOME }}/Software/SimpleFox"
firefox_simplefox_git_repo: "https://github.com/thijssesc/SimpleFox.git"
