---
dependencies: []

galaxy_info:
  author: thisless
  description: Personal aur packages installer.
  license: "MIT"
  min_ansible_version: "2.4"
  platforms:
    - name: ArchLinux
      versions:
        - all
  galaxy_tags: []
