---
- name: Converge
  hosts: all
  gather_facts: false

  roles:
    - role: aur
      vars:
        aur_installed_packages:
          - touchegg
        aur_services:
          - touchegg
        aur_cache: /var/cache/yay
