---
- name: Get mirrorlist.
  become: true
  ansible.builtin.get_url:
    dest: /etc/pacman.d/mirrorlist
    url: https://archlinux.org/mirrorlist/?country=NL&protocol=https&ip_version=4
    mode: "0644"
    owner: root
    group: root

- name: Update pacman cache.
  become: true
  community.general.pacman:
    update_cache: true

- name: Clear pacman cache.
  become: true
  ansible.builtin.shell:
    cmd: yes | pacman -Scc  # noqa risky-shell-pipe
