---
- name: Create the aur user.
  become: true
  ansible.builtin.user:
    name: "{{ aur_user }}"
    create_home: true
    group: wheel

- name: Allow the aur user to run 'sudo pacman' without a password.
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/11-aur-{{ aur_user }}"
    line: "%wheel ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: true
    validate: "visudo -cf %s"
    mode: "0750"

- name: Install base-devel.
  become: true
  community.general.pacman:
    name: base-devel
    state: present
  notify: Update pacman cache for aur.

- name: Install yay.
  become: true
  become_user: "{{ aur_user }}"
  kewlfft.aur.aur:
    name: yay
    state: present
    use: makepkg

- name: Install aur packages.
  become: true
  become_user: "{{ aur_user }}"
  kewlfft.aur.aur:
    name: "{{ aur_installed_packages }}"
    state: present
    use: yay
  when: aur_installed_packages | length > 0

- name: Enable services.
  become: true
  ansible.builtin.service:
    enabled: true
    state: started
    name: "{{ item }}"
  loop: "{{ aur_services }}"

- name: Clear yay cache.
  ansible.builtin.shell:
    cmd: yes | yay -Sc  # noqa risky-shell-pipe
  register: yay_cache_result
  failed_when: yay_cache_result.rc > 1
  changed_when: false
