---
- name: Create the aur user.
  become: true
  ansible.builtin.user:
    name: "{{ aur_user }}"
    create_home: true
    group: wheel

- name: Allow the aur user to 'sudo' without a password.
  become: true
  ansible.builtin.lineinfile:
    dest: "/etc/sudoers"
    regexp: "^# %wheel ALL=\\(ALL:ALL\\) NOPASSWD: ALL"
    line: "%wheel ALL=(ALL:ALL) NOPASSWD: ALL"
    state: present
    validate: "visudo -cf %s"

- name: Install base-devel.
  become: true
  community.general.pacman:
    name: base-devel
    state: present
  notify: Update pacman cache for aur.

- name: Install yay.
  become: true
  become_user: "{{ aur_user }}"
  kewlfft.aur.aur:
    name: yay
    state: present
    use: makepkg

- name: Install aur packages.
  become: true
  become_user: "{{ aur_user }}"
  kewlfft.aur.aur:
    name: "{{ aur_installed_packages }}"
    state: present
    use: yay
  when: aur_installed_packages | length > 0
  notify: Clear yay cache.

- name: Enable services.
  become: true
  ansible.builtin.service:
    enabled: true
    state: started
    name: "{{ item }}"
  loop: "{{ aur_services }}"
