---
- name: Create the 'aur_builder' user.
  become: true
  ansible.builtin.user:
    name: aur_builder
    create_home: true
    group: wheel

- name: Allow the 'aur_builder' user to run 'sudo pacman' without a password.
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: true
    validate: 'visudo -cf %s'
    mode: "0750"

- name: Install base-devel.
  become: true
  community.general.pacman:
    name: base-devel
    state: present
  notify: Update pacman cache.

- name: Install yay.
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: yay
    state: present
    use: makepkg

- name: Install aur packages.
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: "{{ aur_installed_packages }}"
    state: present
    use: yay
  when: aur_installed_packages | length > 0

- name: Enable services.
  become: true
  ansible.builtin.service:
    enabled: true
    state: started
    name: "{{ item }}"
  loop: "{{ aur_services }}"
