---
- name: Set time zone.
  ansible.builtin.file:
    src: "/usr/share/zoneinfo/{{ system_region }}/{{ system_city }}"
    dest: /etc/localtime
    state: link

- name: Set locale-gen localization.
  ansible.builtin.lineinfile:
    dest: /etc/locale.gen
    regexp: "^{{ system_locale }}.UTF-8 UTF-8"
    insertafter: "^#{{ system_locale }}.UTF-8 UTF-8"
    line: "{{ system_locale }}.UTF-8 UTF-8"
    state: present
  notify: Run locale-gen.

- name: Set locale.conf localization.
  ansible.builtin.lineinfile:
    dest: /etc/locale.conf
    regexp: "^LANG={{ system_locale }}.UTF-8"
    line: "LANG={{ system_locale }}.UTF-8"
    state: present

- name: Set hostname.
  ansible.builtin.lineinfile:
    dest: /etc/hostname
    regexp: "^{{ system_hostname }}"
    line: "{{ system_hostname }}"
    state: present
  tags: [molecule-notest]

- name: Install zsh.
  community.general.pacman:
    name: zsh
    state: present

- name: System user.
  ansible.builtin.user:
    name: "{{ system_user }}"
    shell: /usr/bin/zsh
    groups: users,wheel
    append: true
    state: present
