---
- name: Converge
  hosts: all
  gather_facts: false

  roles:
    - role: neovim
      vars:
        neovim_bootstrap_result: /root/.local/share/nvim/lazy
        neovim_mason_cmd: >
          nvim --headless "+Lazy! load mason" "+MasonInstall shellcheck" +quitall
        neovim_mason_result: /root/.local/share/nvim/mason
