---
- name: Prepare
  hosts: all
  gather_facts: false

  pre_tasks:
    - name: Update pacman cache.
      community.general.pacman:
        update_cache: true

    - name: Ensure neovim config folder exists.
      become: true
      ansible.builtin.file:
        path: /root/.config/nvim
        state: directory
        mode: "0755"

    - name: Copy test nvim config.
      ansible.builtin.copy:
        src: files/init.lua
        dest: /root/.config/nvim/init.lua
        mode: "0644"
