---
- name: Converge
  hosts: all
  gather_facts: false

  roles:
    - role: work
      vars:
        work_ssh_keys:
          - name: personal
            host: github.com
            user: root
        work_ssh_user: root
