---
- name: Get current mirrorlist.
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/pacman.d/mirrorlist
    line: "## Netherlands"
    state: present
  notify: Get mirrorlist.

- name: Ensure mirrorlist is updated.
  ansible.builtin.meta: flush_handlers

- name: Enable mirrorlist.
  become: true
  ansible.builtin.replace:
    path: /etc/pacman.d/mirrorlist
    regexp: "^#Server ="
    replace: "Server ="
  notify: Update pacman cache.

- name: Check if multilib repository is available.
  ansible.builtin.lineinfile:
    dest: /etc/pacman.conf
    regexp: "^#\\[multilib\\]"
    line: "[multilib]"
    state: present
  check_mode: true
  register: multilib_available

- name: Enable multilib repository.
  when: >
    multilib_available.changed
    and multilib_available.msg == "line replaced"
  notify: Update pacman cache.
  block:
    - name: Enable multilib repository header.
      become: true
      ansible.builtin.lineinfile:
        dest: /etc/pacman.conf
        regexp: "^#\\[multilib\\]"
        line: "[multilib]"
        state: present

    - name: Enable multilib repository options.
      become: true
      ansible.builtin.lineinfile:
        dest: /etc/pacman.conf
        regexp: "^#Include = /etc/pacman.d/mirrorlist"
        insertafter: "^\\[multilib\\]"
        line: "Include = /etc/pacman.d/mirrorlist"
        state: present

- name: Enable ilovecandy setting.
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/pacman.conf
    regexp: "^ILoveCandy"
    insertafter: "^#UseSyslog"
    line: "ILoveCandy"
    state: present

- name: Ensure cache is updated.
  ansible.builtin.meta: flush_handlers

- name: Install pacman packages.
  become: true
  community.general.pacman:
    name: "{{ pacman_installed_packages }}"
    state: present
  when: pacman_installed_packages | length > 0

- name: Enable services.
  become: true
  ansible.builtin.service:
    enabled: true
    state: started
    name: "{{ item }}"
  loop: "{{ pacman_services }}"

- name: Check if pacman cache is empty.
  ansible.builtin.find:
    paths: /var/cache/pacman/pkg
    file_type: file
  register: pacman_cache_files
  changed_when: pacman_cache_files.files | length > 0

- name: Clear pacman cache.
  become: true
  ansible.builtin.shell:
    cmd: yes | pacman -Scc  # noqa risky-shell-pipe
  when: pacman_cache_files.files | length > 0
  changed_when: pacman_cache_files.files | length > 0
