---
- name: Get current mirrorlist.
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/pacman.d/mirrorlist
    line: '## Netherlands'
    state: present
  notify: Get mirrorlist.

- name: Ensure mirrorlist is updated.
  ansible.builtin.meta: flush_handlers

- name: Enable mirrorlist.
  become: true
  ansible.builtin.replace:
    path: /etc/pacman.d/mirrorlist
    regexp: '^#Server ='
    replace: 'Server ='
  notify: Update pacman cache.

# TODO: Only enable when multilib is available and put in in a block.
- name: Enable multilib repository.
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/pacman.conf
    regexp: '^\\[multilib\\]'
    insertafter: '^#\\[multilib\\]'
    line: '[multilib]'
    state: present
  notify: Update pacman cache.

- name: Enable multilib repository (cont).
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/pacman.conf
    regexp: '^Include = /etc/pacman.d/mirrorlist'
    insertafter: '^\\[multilib\\]'
    line: 'Include = /etc/pacman.d/mirrorlist'
    state: present
  notify: Update pacman cache.

- name: Enable ilovecandy setting.
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/pacman.conf
    regexp: '^ILoveCandy'
    insertafter: '^NoProgressBar'
    line: 'ILoveCandy'
    state: present

- name: Ensure cache is updated.
  ansible.builtin.meta: flush_handlers

- name: Install pacman packages.
  become: true
  community.general.pacman:
    name: "{{ pacman_installed_packages }}"
    state: present
  when: pacman_installed_packages | length > 0

- name: Enable services.
  become: true
  ansible.builtin.service:
    enabled: true
    state: started
    name: "{{ item }}"
  loop: "{{ pacman_services }}"
