---
- name: Ensure ~/.ssh directory exists.
  ansible.builtin.file:
    path: ~/.local/scripts
    state: directory
    mode: "0755"

- name: Create secrets script.
  ansible.builtin.copy:
    src: shell/scr
    dest: ~/.local/scripts
    mode: "0700"

- name: Create vpn script.
  ansible.builtin.copy:
    src: shell/opc
    dest: ~/.local/scripts
    mode: "0744"
