---
- name: Ensure ~/.ssh directory exists.
  ansible.builtin.file:
    path: ~/.local/scripts
    state: directory
    mode: "0755"
    group: "{{ work_user }}"
    owner: "{{ work_user }}"

- name: Create secrets script.
  ansible.builtin.copy:
    src: shell/scr
    dest: ~/.local/scripts
    mode: "0700"
    group: "{{ work_user }}"
    owner: "{{ work_user }}"

- name: Create vpn script.
  ansible.builtin.copy:
    src: shell/opc
    dest: ~/.local/scripts
    mode: "0744"
    group: "{{ work_user }}"
    owner: "{{ work_user }}"
