---
work_github_fileglob: "files/ssh/id_*.pub"
work_github_logging_disabled: true
work_github_repositories: []

work_ssh_fileglob: "files/ssh/id_*"
work_ssh_passphrase: ''

work_user: "{{ ansible_user }}"
