---
- name: Find patches.
  ansible.builtin.find:
    paths: "{{ suckless_git_dest }}/{{ suckless_tool }}/patches"
  register: found_patches

- name: Apply patches.
  ansible.posix.patch:
    basedir: "{{ suckless_git_dest }}/{{ suckless_tool }}"
    src: "{{ item }}"
    remote_src: true
    strip: 1
    state: present
  loop: "{{ found_patches.files | map(attribute='path') | sort }}"

- name: Build tool.
  become: true
  community.general.make:
    chdir: "{{ suckless_git_dest }}/{{ suckless_tool }}"
    target: "{{ item }}"
  loop:
    - clean
    - install
