---
- name: Install neovim.
  become: true
  community.general.pacman:
    name: neovim
    state: present

- name: Install plugin dependencies.
  become: true
  community.general.pacman:
    name:
      - curl
      - git
      - ripgrep
      - tar
      - unzip
    state: present

- name: Install neovim plugins.
  ansible.builtin.command:
    cmd: "{{ neovim_bootstrap_cmd }}"
    creates: "{{ neovim_bootstrap_result }}"

- name: Run Mason.
  block:
    - name: Check if Mason has been run.
      ansible.builtin.stat:
        path: "{{ neovim_mason_result }}"
      register: neovim_mason_directory

    - name: Install nodejs and npm.
      become: true
      community.general.pacman:
        name:
          - nodejs
          - npm
        state: present
      when: not neovim_mason_directory.stat.exists

    - name: Install Mason plugins.
      ansible.builtin.command:
        cmd: "{{ neovim_mason_cmd }}"
        creates: "{{ neovim_mason_result }}"
      notify: Uninstall nodejs and npm.
