---
- name: Install neovim.
  become: true
  community.general.pacman:
    name: neovim
    state: present

- name: Install plugin dependencies.
  become: true
  community.general.pacman:
    name:
      - curl
      - git
      - ripgrep
      - tar
      - unzip
    state: present

- name: Install neovim plugins.
  ansible.builtin.command:
    cmd: "{{ neovim_bootstrap_cmd }}"
    creates: "{{ neovim_bootstrap_result }}"

- name: Install Mason plugins.
  ansible.builtin.command:
    cmd: "{{ neovim_mason_cmd }}"
    creates: "{{ neovim_mason_result }}"
