---
# .github/workflows/ci.yml

name: CI

# yamllint disable-line rule:truthy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: "dots-ansible"
      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install test dependencies.
        run: pip3 install ansible-lint yamllint
      - name: Lint code with yamllint.
        working-directory: dots-ansible
        run: yamllint .
      - name: Lint code with ansible-lint.
        working-directory: dots-ansible
        run: ansible-lint

  molecule:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        role:
          - aur
          - dash
          - dots
          - firefox
          - neovim
          - pacman
          - suckless
          - system
          - work

    steps:
      - name: Check out the code base.
        uses: actions/checkout@v3
        with:
          path: "dots-ansible"
      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-plugins[docker] docker
      - name: Setup ansible-vault password file.
        run: printf '%s' "${{ secrets.ANSIBLE_VAULT }}" > "$GITHUB_WORKSPACE/.ansible_vault"
      - name: Run Molecule tests.
        working-directory: dots-ansible/roles/${{ matrix.role }}
        run: molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          ANSIBLE_VAULT_PASSWORD_FILE: "$GITHUB_WORKSPACE/.ansible_vault"
